### PR TITLE
News page creation

### PR DESCRIPTION
**Pull request by Sisha3342**
Added news page (authorized user). Also, is there a better way (i used @media and multiple times rescaled selectors) to "scale" the page for mobile phone users?

### CODE REVIEW

**Comment by MaksimViarenich** [comment]
Something went wrong with your page)
image

**Comment by MaksimViarenich** [comment]
Inputs are not clickable

**Comment by MaksimViarenich** [comment]
We should discuss everything in the lesson with you.

**Comment by MaksimViarenich** [comment]
Remove inline styles

**Comment by AlexeSemenenko** [comment]
gj

**Comment by MaksimViarenich** [comment]
Merge PR, please)

**Pull request merged**
