### PR TITLE
Mockups branch

### PR DESCRIPTION
**Pull request by Sisha3342**
Finished task 2

### CODE REVIEW

**Comment by MaksimViarenich** [comment]
For future
Better to name branch not in CamelCase.
Example: create_mockups

**Comment by MaksimViarenich** [comment]
Add me as a reviewer, pls

**Comment by Sisha3342** [comment]
> Add me as a reviewer, pls

Good evening, Maksim! If I got everything right, before adding you as a reviewer, you need to become a collaborator of this repository. I've already sent you an invite. If i'm wrong, please tell me how to do this correctly

**Comment by MaksimViarenich** [comment]
> > Add me as a reviewer, pls
> 
> Good evening, Maksim! If I got everything right, before adding you as a reviewer, you need to become a contributor of this repository. I've already sent you an invite. If i'm wrong, please tell me how to do this correctly

**Comment by MaksimViarenich** [comment]
This doesn't exist in Technickal requirements. 
Снимок экрана 2020-02-24 в 23 11 24

**Comment by MaksimViarenich** [comment]
Incorrect footer
Снимок экрана 2020-02-24 в 23 13 13

**Comment by MaksimViarenich** [comment]
Снимок экрана 2020-02-24 в 23 14 04

**Comment by MaksimViarenich** [comment]
Can't find logic for delete
Снимок экрана 2020-02-24 в 20 43 37

**Comment by MaksimViarenich** [comment]
Also can't find the logic for guest

**Comment by MaksimViarenich** [comment]
Error is a page, not icon with tooltip
Снимок экрана 2020-02-24 в 23 21 49

**Pull request closed without merging**
